# Site Settings
title: Harmony Documentation
version: 1.0.2
oldversion: 1.0.1
email: bettadevindonesia@gmail.com
description: >
  Harmony Framework is a PHP framework built under the Slim Framework. Harmony is a unit of some famous packages that have been widely used by developers in the world. Initially Harmony Framework was built for personal purposes to facilitate my work as a website developer, but I also want Harmony Framework can be useful for other developers.
baseurl: ""
url: "https://harmony-betta.github.io"
twitter_username: bettadevindonesia
github_username:  harmony-betta
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
collections:
  subpages:
    output: true
kramdown:
  input: GFM