# Site Settings
title: Harmony Documentation
version: 1.0.2
oldversion: 1.0.1
email: bettadevindonesia@gmail.com
description: >
  A guide to getting started with Harmony Framework.
baseurl: ""
url: "http://localhost:4000"
twitter_username: bettadevindonesia
github_username:  harmony-betta
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
collections:
  subpages:
    output: true
kramdown:
  input: GFM